Ocaml generator
prologin/stechec2 pull request #135
Opened 2020-04-30 22:50 UTC by FardaleM

I am starting to work on the ocaml generator and I will see what I can do.

2020-08-21 12:21 UTC, seirl requested changes
Overall good changes, I have some minor issues with two commits. Thanks for the PR!

2020-08-21 12:21 UTC, seirl commented on tools/generator/templates/player/caml/interface.cc.jinja2
> +    {%if struct.str_field|caml_test_float_struct %}
nit: missing space

2020-08-21 12:21 UTC, seirl commented on tools/generator/filters/caml.py
> +@register_filter
This should be a test instead. Use `@register_test` like this:

```python
@register_test
def caml_full_float_struct(s) -> bool:
    [...]
```

and use it like this in the template:

```jinja2
{% if struct is caml_full_float_struct %}
```

Also, the interface is nicer if you take the struct in parameter directly, instead of str_fields.

2020-08-21 12:21 UTC, seirl commented on tools/generator/test/languages/champion.ml
> +    send_me_double_struct { field_one = 42.42; field_two = 42.42 };
Are you willing to add this to all the other test champions? It doesn't look like a ton of work, and it would allow you to check that the function is correctly called in all the languages.

I know we should probably have a way to specify language-specific tests, but in the meantime doing that isn't really difficult.

2020-08-21 12:21 UTC, seirl commented on tools/generator/templates/player/caml/api.ml.jinja2
> +(*{%- set product = joiner(' , ') -%}
"product"?

2020-08-21 12:21 UTC, seirl commented on tools/generator/templates/player/caml/champion.ml.jinja2
> +    flush stdout{{ func.fct_ret_type|caml_default_value }}
I don't think I like having a default value here. The only benefit is that it compiles from the start, but these functions should be changed anyway to remove the buggy default values, so why put them in the first place?

Also, it will only work for functions that don't return a special type, and it already worked for unit functions, which are the only ones we really support right now.

2020-08-23 11:32 UTC, seirl requested changes
Could you just revert your change of documentation order after the functions? https://caml.inria.fr/pub/docs/manual-ocaml/ocamldoc.html puts the documentation before the signatures, and it's more consistent with the other languages.

Other than that and another nitpick, LGTM

2020-08-23 11:32 UTC, seirl commented on tools/generator/templates/player/caml/api.ml.jinja2
> +(*{%- set comma = joiner(', ') -%}
Missing spaces after `(*` and before `*)`

2020-08-24 17:28 UTC, FardaleM commented
> Could you just revert your change of documentation order after the functions? https://caml.inria.fr/pub/docs/manual-ocaml/ocamldoc.html puts the documentation before the signatures, and it's more consistent with the other languages.
I don't see where ocamldoc puts documentation before signatures. If you speak about examples in the doc, there are comment before and after. Actually the rule to associate a comment with a element is simpler if the comment is bellow the element which can prevent future problem.

2020-08-24 18:03 UTC, seirl approved these changes

2020-08-24 18:03 UTC, merged

2020-08-24 18:03 UTC, seirl commented
Thanks!