rules: Action: Add a virtual method dump_json
prologin/stechec2 pull request #138
Opened 2020-05-05 19:42 UTC by fnareoh

Add an optional virtual method to output the json dump for an action, in
order to make the dump process more elegant for the rules that use this feature.

This way for the list of actions to dump you can just call `action.dump_json(gamestate)`.

2020-07-11 02:12 UTC, multun approved these changes
LGTM

2020-07-11 02:12 UTC, multun commented on tools/generator/templates/rules/src/action_template.hh.jinja2
> +    void dump_json(const GameState& st, std::ostream& ss) const;
I think I'd be slightly better with an `override`

2020-07-11 09:07 UTC, seirl commented
Hmm, why don't we reuse handle_buffer instead of having to write that function manually?

2020-07-29 12:30 UTC, seirl requested changes
As explained above, this should use handle_buffer instead of reimplementing twice the serialization of each action.

2022-07-31 15:01 UTC, juli0z commented
Migrated to https://gitlab.com/prologin/tech/tools/stechec2/-/merge_requests/138

2022-07-31 15:01 UTC, closed without merging